Metrics
farazali7/real-time-video-captioning pull request #2
Opened 2024-02-26 17:04 UTC by Paanugoban

This adds a few functions to be able to do metrics found in GIT (Bleu, Rouge, Meteor and CIDER-D). I found many implementations of these models, but I used the natural language toolkit that comes with python and a brand new package on python that you would have to install manually, https://pypi.org/project/aac-metrics/. The template in which you would ask these functions can be found in the comments in the function or test function below. Preliminary testing seems to suggest it works, but if it doesn't, we can also adjust to use hugging face evaluate and use another package that outputs (Bleu and Rouge). However for CIDER-D its difficult to find alternatives. The implementation of all these manually seemed complex, that I thought it's better to work off something that was implemented to ensure its working.

2024-02-27 02:40 UTC, farazali7 requested changes
Good work. Just some small change requests before we merge this in.

2024-02-27 02:40 UTC, farazali7 commented on src/metrics.py
> +    #['The cat is on the mat','The cat is not on the mat']
Try to follow standard documentation format for function docs, like this for ex: https://github.com/farazali7/multimodal-xray/blob/99a267faf6980217b7308021e09c6aa9441d06e3/src/models/attention.py#L11

2024-02-27 02:40 UTC, farazali7 commented on src/metrics.py
> +        print("Error occurred:", e.stderr)
This is a bit awkward... any alternatives for CIDEr score without having to invoke the shell via this package?

2024-02-27 02:40 UTC, farazali7 commented on src/metrics.py
> +#test_metrics()
NP: Create a tests/ folder outside of src (in root project directory) and move this function inside of a test_metrics.py file.

2024-02-27 02:41 UTC, farazali7 commented on src/metrics.py
> +        print("Error occurred:", e.stderr)
If not or seems like a lot of effort right now, then let's just revisit this metric a little later.

2024-02-27 21:06 UTC, Paanugoban commented
@farazali7 I have the suggested changes to the code

2024-03-04 22:12 UTC, farazali7 approved these changes

2024-03-04 22:14 UTC, merged